services:
  - type: web
    name: messenger-bot
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:$PORT callback.php"
    envVars:
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: OPENAI_KEY
        sync: false

